### ISSUE TITLE
Xelatex font problem since 4.32

### ISSUE THREAD

**Issue by ib1986** [T-F-S/tcolorbox#120]
The color of the font is changed to white _after_ the final part of the box when the box is broken. Minimal exemple :

\documentclass{minimal}
\usepackage{tcolorbox}
\tcbuselibrary{breakable}
\usepackage{lipsum}
\newtcolorbox{test}{breakable} 
\begin{document}
\begin{test}
    \lipsum
\end{test}
This is written in white.
\end{document}

With pdflatex the last line is shown (_i.e._ "This is written in white."), not with xelatex.

**Comment by T-F-S** [comment]
Unfortunately, xelatex does not support color stacks which are used since `tcolorbox v4.32` for breakable boxes, see https://github.com/T-F-S/tcolorbox/issues/110. 

The implementation changed at several places and introduced this new error for xelatex.

I tried some hacks I used before. It seems that it is enough to reset the current color with `\color{.}` at the end of all things.

```latex
The following works for me:

\documentclass{minimal}
\usepackage{\tcbpkgprefix tcolorbox}
\tcbuselibrary{breakable}
\usepackage{lipsum}

\makeatletter
\def\tcb@finalize@environment{%
  \color{.}% hack for xelatex
  \tcb@layer@dec%
}
\makeatother

\newtcolorbox{test}{breakable,colupper=blue}
\begin{document}
\begin{test}
\lipsum
\end{test}
This is written (not any longer) in white.
\end{document}
```

Does this patch work for your application?

**Comment by ib1986** [comment]
Yes, it's working with this hack.

**Comment by muzimuzhi** [comment]
I'm not sure but this might be a `xdvipdfmx` bug. 

To simplify the output, the following example is used.
```tex
% test.tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{breakable, skins}
\usepackage{lipsum}

\begin{document}
\font\x=cmr10 at 10pt\x
This is written in \color{red}red.

\begin{tcolorbox}[breakable, break at=80pt, empty]
  \lipsum[2]
\end{tcolorbox}

This is written in white.
\end{document}
```
In the output pdf, input `This is written in white.` is in white. This can be confirmed by converting `test.pdf` to human readable (and editable) form, by running `mutool clean -ad test.pdf test-editable.pdf` (get `mutool` from www.mupdf.com).

In lines beginning with `13 0 obj`, you can find, in reindented form,
```
13 0 obj
<<
  /Length 1452
>>
stream
  q
    1 0 0 1 72 720 cm
    1 G 1 g 0 G 0 g 1 G 1 g
    q
      [...]
    Q 
    BT
      /F1 9.9626 Tf 76.712 -119.757 Td[(This)-333(is)-333(written)-334(in)-333(white.)]TJ ET 0 G 0 g BT 
      /F2 9.9626 Tf 231.133 -630.635 Td[<006b>]TJ
    ET 
    1 0 0 RG 1 0 0 rg 
  Q

endstream
endobj
```

Here pdf literals
 - `q` pushes current state to a stack, and `Q` pops from that stack;
 - `1 G 1 g` sets color to white in gray color space, and `0 G 0 g` sets color to black;
 - `1 0 0 RG 1 0 0 rg` sets color to red in rgb color space;
 - `BT` and `ET` constructs a text object, which is text `This is written in white.` in our example.

Hence in the output of `xdvipdfmx`, the text `This is written in white.` is in white, a color never specified in tex source.

Run `xelatex -no-pdf test.tex` followed by `dviasm test.xdv > test.dump` ([`dviasm`](https://ctan.org/pkg/dviasm) is a python script available on CTAN), the human readable `test.dump` shows color white is never specified in `test.xdv`, the input of `xdvipdfmx`.

Therefore I guess the problem comes from `xdvipdfmx`. I haven't found a further simplified tex example, hence a bit hesitate to report this to the mailing list of `xdvipdfmx`, dvipdfmx@tug.org.

**Comment by T-F-S** [comment]
Solved by version 4.41 (2020/09/29).

**Comment by muzimuzhi** [comment]
With xelatex + tcolorbox 4.41, this example from https://tex.stackexchange.com/q/565790 still fails:

```tex
\documentclass{article}
\usepackage[breakable]{tcolorbox}
\usepackage{lipsum}

\begin{document}
{
  \begin{tcolorbox}[breakable]
    \lipsum
  \end{tcolorbox}
}

text in white
{\bfseries\color{orange} problem: after broken box inside a group, textcolor is white}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/95522065-b13ef080-09fd-11eb-9773-b13ae35e0090.png)

**Comment by T-F-S** [comment]
I am preparing a rollback of the coloring algorithm (mainly) to pre 4.32 which should solve this problem finally.

**Comment by T-F-S** [comment]
Resolved (finally?) with version 4.42 (2020-10-09).
