### ISSUE TITLE
Combination of `amsmath`, `cleveref` and the `tcolorbox` documentation library is broken with LaTeX2e <2025-06-01>

### ISSUE THREAD

**Issue by T-F-S** [T-F-S/tcolorbox#318]
With `LaTeX2e <2025-06-01>` the handling of \label was improved. This broke the combination of `amsmath`, `cleveref` and the `tcolorbox` documentation library.

Consider the following MWE:

```latex
\documentclass{article}

\usepackage{tcolorbox}

%\tcbuselibrary{theorems}
\usepackage{amsmath}

\tcbuselibrary{documentation}

\usepackage{cleveref}

\begin{document}

\begin{docCommand}{foomakedocSubKey}{\marg{name}\marg{key path}}
  Test
\end{docCommand}

See \refCom{foomakedocSubKey}

\end{document}
```

![Image](https://github.com/user-attachments/assets/3a743dbc-dc55-47a2-b797-18613fb4e038)

Removing either `amsmath` or `cleveref` gives the expected result:

![Image](https://github.com/user-attachments/assets/1f95f701-9782-4681-ab5e-5170caad2881)

Currently, the `tcolorbox` package documentation cannot be compiled because of this problem.

**Comment by mbertucci47** [comment]
Further reduction:
```tex
\documentclass{article}

\usepackage{tcolorbox}

\makeatletter
\let\@xp\expandafter
% from amsmath.sty
\let\ltx@label\label
\toks@\@xp{\@arrayparboxrestore \let\label\ltx@label}%
\edef\@arrayparboxrestore{\the\toks@}

\usepackage{cleveref}

% from cleveref amsmath patch
\def\ltx@label#1{\cref@label#1}%

\begin{document}

\show\label

\begin{tcolorbox}
\show\label

\label{somelabel}
\end{tcolorbox}

\end{document}
```
If the line
```tex
\def\ltx@label#1{\cref@label#1}%
```
in cleveref.sty is changed to
```tex
\def\ltx@label#1{\cref@label{#1}}%
```
then your original tcb doc example works as expected.

**Comment by T-F-S** [comment]
@mbertucci47 Thank you very much for reducing the problem to its kernel. This is really helpful!

From your report to latex2e I saw that by https://github.com/latex3/latex2e/issues/1684 the problem is known for three month, but the first aid patch of Ulrike Fischer is not active yet. 

I tested your patch and the longer patch from u-fischer. It works for the documentation macros, but the theorem examples where `cleveref` is really used are still defect. Maybe, that is part of the reason why the patch is not part of the first aid package yet.

I used `cleveref` for many years, but I am thinking to switch to `zref-clever` now. In https://github.com/latex3/latex2e/issues/1684, there is a post about migration to `zref-clever` which may be helpful for others having problems right now.

**Comment by mbertucci47** [comment]
@T-F-S Happy to help. I switched to zref-clever in my package [documentation](https://github.com/mbertucci47/keytheorems/blob/develop/doc/keytheorems-doc.tex) as well as my thesis, and it's been a breeze. All the features of cleveref without any of the issues and an active maintainer

**Comment by muzimuzhi** [comment]
Should be fixed with `first-aid` 2025/06/05, v1.1p.

`first-aid` provides `latex2e-first-aid-for-external-files.ltx` which is packed into the LaTeX format, thus it's a bit hard to detect its version

```tex
\makeatletter
\@ifl@t@r\LaTeXFirstAidDate{2025/06/5}
  {}{\ERROR}
\makeatother
```

**Comment by T-F-S** [comment]
> Should be fixed with `first-aid` 2025/06/05, v1.1p

No, unfortunately, this does not fix the problem with the example from my first post (tested just now) ...

**Comment by mbertucci47** [comment]
@T-F-S It seems to be fixed on my end. The example works as expected

**Comment by T-F-S** [comment]
> It seems to be fixed on my end. The example works as expected

Seems that I the update had not reached my system yesterday for some reason. Today I got a new update and now the example works as expected also for me :-)
